Flavorique Web App/Models/PrintViewModel.cs
namespace Flavorique_Web_App.Models
{
	public class PrintViewModel
	{
        public string Image { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Body { get; set; }
    }
}

Flavorique Web App/Models/Recipe.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace Flavorique_Web_App.Models
{
    public class Recipe
    {
        [Key]
        public int Id {  get; set; }
        [Required]
        [StringLength(100)]
        public string? Title { get; set; }
        [Required]
        public string? Body { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
        public string? AuthorId { get; set; }
        public ApplicationUser? Author { get; set; }
    }
}

Flavorique Web App/Controllers/RecipeController.cs
using Flavorique_Web_App.Data;
using Flavorique_Web_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Xml.Linq;
using Newtonsoft.Json;
using TXTextControl;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;

namespace Flavorique_Web_App.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RecipeController : ControllerBase
    {
        private readonly ILogger<RecipeController> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly HTMLToPDFConverter _htmlToPDFConverter;

        public RecipeController(ILogger<RecipeController> logger, ApplicationDbContext db, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, HTMLToPDFConverter htmlToPDFConverter)
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
            _htmlToPDFConverter = htmlToPDFConverter;
        }

        // GET: api/Recipe
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ShortRecipe>>> GetRecipes(string? sortOrder, string? searchString, int? pageNumber, int pageSize = 5)
        {
            try
            {
                var query = _db.Recipes.Select(i => new ShortRecipe
                {
                    Id = i.Id,
                    AuthorId = i.AuthorId,
                    Title = i.Title,
                    CreatedDateTime = i.CreatedDateTime,
                    Body = StripHtmlTags(i.Body).Length > 200 ? StripHtmlTags(i.Body).Substring(0, 200) : StripHtmlTags(i.Body),
                    Image = GetImageFromHtml(i.Body),
                });

                var resultTasks = query.ToList().Select(async r => new ShortRecipe
                {
                    Id = r.Id,
                    AuthorId = r.AuthorId,
                    AuthorName = _userManager.FindByIdAsync(r.AuthorId).Result.UserName,
                    Title = r.Title,
                    CreatedDateTime = r.CreatedDateTime,
                    Body = r.Body,
                    Image = r.Image,
                    Rating = GetRecipeRating(r.Id)
                });

                var recipeResult = await Task.WhenAll(resultTasks);

                IEnumerable<ShortRecipe> recipes = recipeResult;

                if (!String.IsNullOrEmpty(searchString))
                {
                    searchString = searchString.ToLower();
                    recipes = recipes.Where(r => r.Title.ToLower().Contains(searchString) ||
                                                  _userManager.Users.Any(u => u.Id == r.AuthorId && u.UserName.ToLower().Contains(searchString)));
                }

                int count = recipes.Count();

                switch (sortOrder)
                {
                    case "title":
                        recipes = recipes.OrderBy(r => r.Title);
                        break;
                    case "titleDesc":
                        recipes = recipes.OrderByDescending(r => r.Title);
                        break;
                    case "date":
                        recipes = recipes.OrderBy(r => r.CreatedDateTime);
                        break;
                    case "dateDesc":
                        recipes = recipes.OrderByDescending(r => r.CreatedDateTime);
                        break;
                    case "rating":
                        recipes = recipes.OrderByDescending(r => r.Rating.Rating);
                        break;
                    case "ratingDesc":
                        recipes = recipes.OrderBy(r => r.Rating.Rating);
                        break;
                    case "idDesc":
                        recipes = recipes.OrderByDescending(r => r.Id);
                        break;
                    default:
                        recipes = recipes.OrderBy(r => r.Id);
                        break;
                }

                PaginatedList<ShortRecipe> result = await PaginatedList<ShortRecipe>.CreateAsync(recipes, pageNumber ?? 1, pageSize);

                _logger.LogInformation(result.ToString());

                return Ok(new { data = result, pageIndex = result.PageIndex, totalPages = result.TotalPages, count = count });
            }
            catch (Exception ex)
            {
                _logger.LogError($"An error occurred: {ex}");
                return StatusCode(500, "Internal server error");
            }
        }

        // GET: api/Recipe/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Recipe>> GetRecipe(int id)
        {
            if (_db.Recipes == null)
            {
                return NotFound();
            }
            var recipe = await _db.Recipes.FindAsync(id);

            if (recipe == null)
            {
                return NotFound();
            }
            return recipe;
        }

        [HttpGet("category/{id}")]
        public async Task<ActionResult> GetRecipesByCategory(int id)
        {
            if (_db.Recipes == null)
            {
                return NotFound();
            }

            var tags = await _db.Tags.Where(t => t.CategoryId == id).Select(t => t.Id).ToListAsync();

            var result = await _db.RecipeTags.Include(m => m.Recipe).Where(t => tags.Contains(t.TagId)).Select(t => t.Recipe).Distinct().ToListAsync();

            var recipeTasks = result.ToList().Select(async i => new ShortRecipe
            {
                Id = i.Id,
                AuthorId = i.AuthorId,
                Title = i.Title,
                CreatedDateTime = i.CreatedDateTime,
                Body = StripHtmlTags(i.Body).Length > 200 ? StripHtmlTags(i.Body).Substring(0, 200) : StripHtmlTags(i.Body),
                Image = GetImageFromHtml(i.Body),
                Rating = GetRecipeRating(i.Id)
            });

            var recipes = await Task.WhenAll(recipeTasks);

            return Ok(recipes);
        }

        [HttpGet("tag/{id}")]
        public async Task<ActionResult> GetRecipesByTags(int id)
        {
            if (_db.Recipes == null)
            {
                return NotFound();
            }

            var result = await _db.RecipeTags.Include(m => m.Recipe).Where(t => t.TagId == id).Select(t => t.Recipe).ToListAsync();

            var recipeTasks = result.ToList().Select(async i => new ShortRecipe
            {
                Id = i.Id,
                AuthorId = i.AuthorId,
                Title = i.Title,
                CreatedDateTime = i.CreatedDateTime,
                Body = StripHtmlTags(i.Body).Length > 200 ? StripHtmlTags(i.Body).Substring(0, 200) : StripHtmlTags(i.Body),
                Image = GetImageFromHtml(i.Body),
                Rating = GetRecipeRating(i.Id)
            });

            var recipes = await Task.WhenAll(recipeTasks);

            return Ok(recipes);
        }

        // GET: api/Recipe
        [HttpGet("user/{username}")]
        public async Task<ActionResult> GetRecipesByUserName(string username)
        {
            if (_db.Recipes == null)
            {
                return NotFound();
			}

            var user = await _userManager.FindByNameAsync(username);

			if (user == null)
			{
				return NotFound($"User with username {username} not found.");
			}

            var recipes = await _db.Recipes
                .Where(recipe => recipe.AuthorId == user.Id)
                .OrderByDescending(recipe => recipe.CreatedDateTime)
                .Take(3)
                .ToListAsync();

            var result = recipes.Select(async i => new ShortRecipe
            {
                Id = i.Id,
                Title = i.Title,
                CreatedDateTime = i.CreatedDateTime,
                Body = StripHtmlTags(i.Body).Length > 200 ? StripHtmlTags(i.Body).Substring(0, 200) : StripHtmlTags(i.Body),
                Image = GetImageFromHtml(i.Body),
                Rating = GetRecipeRating(i.Id)
            })
            .ToList();
            
            _logger.LogInformation($"Result count: {result.Count}");

			return Ok(result);
		}

        // GET: api/Recipe/short
        // Shortened version of the recipe, for recommended / other views
        [HttpGet("short")]
        public ActionResult<IEnumerable<object>> GetShortRecipes(int number = 3)
        {
            if (_db.Recipes == null)
            {
                return NotFound();
            }

            var result = _db.Recipes
                .Select(i => new ShortRecipe
                {
                    Id = i.Id,
                    Title = i.Title,
                    CreatedDateTime = i.CreatedDateTime,
                    Body = StripHtmlTags(i.Body).Length > 200 ? StripHtmlTags(i.Body).Substring(0, 200) : StripHtmlTags(i.Body),
                    Image = GetImageFromHtml(i.Body)
                })
                .OrderByDescending(j => j.CreatedDateTime)
                .Take(number)
                .ToList();

            return result;
        }

        // PUT: api/Recipe/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutRecipe(int id, Recipe recipe)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                var user = await _userManager.GetUserAsync(User);

                if (user == null) {
                    return Unauthorized("User not found.");
                }

Flavorique Web App/Views/Recipe/Create.cshtml
@model Recipe

@{
    ViewData["Title"] = "Create";
}
<form onsubmit="setValues()" method="post">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Create Recipe </h2>
            <hr />
        </div>
        <div class="mb-3 d-flex w-100 align-items-center justify-content-between">
            <div class="w-75">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control border-0 border-bottom border-primary" />
            </div>
            <div>
                <div class="mt-3">
                    <button type="button" class="btn btn-light"><i class="bi bi-eye-fill"></i> &nbsp Preview </button>
                    <button type="submit" class="btn btn-primary"><i class="bi bi-send"></i> &nbsp Create </button>
                    <a asp-controller="Recipe" asp-action="Index" class="btn btn-secondary">Go back</a>
                </div>
            </div>
        </div>
        <span asp-validation-for="Title" class="text-danger"></span>
        <span asp-validation-for="Body" class="text-danger"></span>

        <div id="bodyData" class="mb-3 d-none">
            <label asp-for="Body"></label>
            <input asp-for="Body" class="form-control body-input" />
        </div>
        
        <div id="editor">
            <div class="d-flex align-items-center justify-content-center" style="height: 200px;">
                <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status"></div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_CKEditorScriptsPartial" />
    }
}

Flavorique Web App/Views/Recipe/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model Recipe
@{
    ViewData["Title"] = "Details";

}

<div id="spinner" class="d-flex align-items-center justify-content-center" style="height: calc(100vh - 108px)">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status"></div>
</div>

<section id="recipe" class="d-none">

    <section class="append-div ck-content">
        <h1 class="my-5">@Model.Title</h1>
    
        <a href="#ingredients" class="w-100 d-block bg-light text-center p-3 mb-5 text-decoration-none" style="font-size: 20px;"><i class="bi bi-arrow-down"></i> Jump to recipe</a>

        <div class="recipe-body">
            @Html.Raw(@Model.Body)
        </div>
    </section>
    
    <section class="d-flex flex-column align-items-center justify-content-evenly text-center mt-5">
        <h1 class="align-self-start">Similar Recipes</h1>
        <div class="w-100 d-flex flex-column align-items-center justify-content-center">
            @for (var i = 0; i < 3; i++)
            {
                <div class="border-bottom w-75 rounded d-flex align-items-center p-4" style="height:250px">
                    <img class=" h-100" style="aspect-ratio: 1 / 1" />
                    <div class="p-5" style="text-align:left">
                        <p class="text-secondary">November 14, 2023</p>
                        <h3 class="fw-bolder">Title</h3>
                        <p style="text-align: justify">This shredded beef Texas chili is rich and hearty, made with 8 simple ingredients! Just saucy chunks of tender beef that shreds apart with the lightest pull of a fork. YUM.</p>
                        <a asp-controller="Recipe" asp-action="Details" asp-route-id="1" style="font-size: 18px; letter-spacing: 1px">Continue Reading <i class="bi bi-arrow-right"></i></a>
                    </div>
                </div>
            }
        </div>
    </section>
    
    <section class="tag-container d-flex align-items-center mt-5">
        <h4 class="me-3">Tags:</h4>
        
        @for (var i = 10; i < 21; i++)
        {
            <a href="#" class="tag-item p-2 bg-primary text-light rounded">Line @i</a>
        }
    </section>

    @if (SignInManager.IsSignedIn(User))
    {
        <section class="create-comment-container mt-5 p-5 bg-light rounded">
            <h4 class="mb-5">Leave a comment</h4>

            <form method="post">
                <div class="mb-3">
                    <label>Comment</label>
                    <textarea style="min-height: 200px" class="form-control"></textarea>
                    <span class="text-danger"></span>
                </div>
                <div class="mb-3 star-container">
                    <label class="me-3">Recipe rating</label>

                    <fieldset class="star-rating">
                        <input id="star-1" type="radio" name="rating" value="1" />
                        <label for="star-1">
                            <i class="bi bi-star-fill"></i>
                        </label>
                        <input id="star-2" type="radio" name="rating" value="2" />
                        <label for="star-2">
                            <i class="bi bi-star-fill"></i>
                        </label>
                        <input id="star-3" type="radio" name="rating" value="3" />
                        <label for="star-3">
                            <i class="bi bi-star-fill"></i>
                        </label>
                        <input id="star-4" type="radio" name="rating" value="4" />
                        <label for="star-4">
                            <i class="bi bi-star-fill"></i>
                        </label>
                        <input id="star-5" type="radio" name="rating" value="5" />
                        <label for="star-5">
                            <i class="bi bi-star-fill"></i>
                        </label>
                    </fieldset>

                    <span class="text-danger"></span>
                </div>
                <button type="submit" style="letter-spacing: 1px" class="p-3 mt-4 btn btn-primary">Post Comment</button>
            </form>
        </section>
    }

    <section class="main-comment-container mt-5">
        <h4 class="text-primary">50 Comments</h4>
        <hr class="mb-5" />

        <div class="comment-container d-flex flex-column">
            @for (var i = 0; i < 5; i++)
            {
            <div class="comment-item mb-5">
                <div class="d-flex align-items-start">
                    <img src="" class="border rounded-circle" style="width: 100px; aspect-ratio: 1 / 1;"/>
                    <div class="ms-4">
                        <h5>Name</h5>
                        <p style="text-align: justify;">
                            Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content Comment Content 
                        </p>
                    </div>
                </div>

                <div class="d-flex justify-content-between">
                <p class="text-primary">
                    November 14, 2023 &commat; 12:57
                </p>
                <a href="#" class="text-primary">Reply</a>
                </div>

            </div>
            }
        </div>

    </section>

</section>

@section Scripts{
    @{
    <script src="~/assets/vendor/build/ckeditor.js"></script>
    <script>
                                            document.querySelector("#spinner").classList.add("d-none");
                                            document.querySelector("#recipe").classList.remove("d-none");
    </script>

    <script>
                                            let ingredients = document.getElementById("ingredients");
                                            let printBtn = document.createElement("a");
                                            
                                            let i = document.createElement("i");
                                            i.classList.add("bi");
                                            i.classList.add("bi-printer");

                                            printBtn.appendChild(document.createTextNode("Print Recipe "));
                                            printBtn.appendChild(i);
                                            printBtn.classList.add("btn");
                                            printBtn.classList.add("btn-light");
                                            printBtn.style.float = "right";

                        let url =  window.location.href;
                var match = url.match(/\/Details\/(\d+)/);

                            let id = match[1];
                            printBtn.href = `../Print/${id}`;

                                            ingredients.appendChild(printBtn);
    </script>
    }
}

Flavorique Web App/Views/Recipe/Print.cshtml
@using Microsoft.AspNetCore.Identity
@model PrintViewModel
@inject UserManager<ApplicationUser> UserManager
@{
	Layout = null;
}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8" />
	<title>Print Recipe</title>
	<style>
		#printContainer{
			padding: 20px;
			width: 800px;
			border: 5px solid gray;
		}

		#headContainer {
			font-size: 12px;
		}

		img{
			border: 1px solid black;
			width: 150px;
			height: 150px;
			margin: 0;
			border-radius: 50%;
			object-position: center;
			top: 0px;
		}

		tr{
			width: 100%;
		}

		#printTable, #bodyTd{
			border: 5px solid gray;
		}

		td {
			padding: 20px;
		}



	</style>
</head>
<body>
<form id="myForm" asp-controller="Recipe" asp-action="PrintPDF" onsubmit="getValues()" method="post">
	<input type="hidden" id="title" name="title" value="" />
	<input type="hidden" id="body" name="body" value="" />
	<button type="submit">Print</button>
</form>

	<div id="printContainer">
		<table id="printTable" style="border: none; padding: 0px; width: 100%;">
			<tr>
				<td id="headContainer" style="font-size: 18px !important;">
					<h1 id="modelTitle">@Model.Title</h1>
					<p>Author: @Model.Author</p>
					<p>Reviews: ⭐⭐⭐⭐⭐</p>
				</td>
				<td style="padding: 20px;">
					<img src="@Model.Image" style="position: relative !important; right: 0 !important;">
				</td>
			</tr>
			<tr>
				<td id="bodyTd" colspan="2" style="border: none !important">
					@Html.Raw(Model.Body)
				</td>
			</tr>
		</table>
	</div>

<script>
	let divs = document.querySelectorAll("div.ck");
	
	divs.forEach(function (item, index) { 
		item.remove();
	});

	function getValues() { 
		let title = document.getElementById("title");
		let body = document.getElementById("body");

		title.value = document.getElementById("modelTitle").innerText;
		body.value = document.documentElement.outerHTML;
	}
</script>
</body>
</html>