Flavorique MVC/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using Flavorique_MVC.Models;
using Newtonsoft.Json;
using System.Text;
using System.Net;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace Flavorique_MVC.Controllers
{
    public class TagController : Controller
    {
        private readonly ILogger<TagController> _logger;

        public TagController(ILogger<TagController> logger)
        {
            _logger = logger;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, int pageNumber, string categoryFilter)
        {
            var userRole = await GetUserRole();

            if (!userRole.Equals("Admin"))
            {
                return Redirect("https://localhost:7147/Identity/Account/Login?from=r");
            }

            IEnumerable<Tag> tags = new List<Tag>();
            int pageIndex = 1;
            int totalPages = 1;
            int count = 0;

            using (var client = new HttpClient())
            {
                using (var response = await client.GetAsync($"https://localhost:7147/api/Tag?sortOrder={sortOrder}&searchString={searchString}&pageNumber={pageNumber}&category={categoryFilter}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    var responseObject = JsonConvert.DeserializeAnonymousType(apiResponse, new { data = Enumerable.Empty<Tag>(), pageIndex = 1, totalPages = 1, count = 0 });

                    tags = responseObject.data;
                    pageIndex = responseObject.pageIndex;
                    totalPages = responseObject.totalPages;
                    count = responseObject.count;

                    _logger.LogCritical(responseObject.pageIndex.ToString());
                    _logger.LogCritical(pageIndex.ToString());
                }
            }

            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "idDesc" : "";
            ViewData["NameSortParm"] = sortOrder == "name" ? "nameDesc" : "name";
            ViewData["CategorySortParm"] = sortOrder == "category" ? "categoryDesc" : "category";
            ViewData["CategoryFilterParm"] = categoryFilter;
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentSort"] = sortOrder;

            if (pageIndex == 0)
            {
                pageIndex = 1;
            }

            _logger.LogWarning(tags.Count().ToString());

            var paginatedList = new PaginatedList<Tag>(tags.ToList(), count, pageIndex, 5);

            IEnumerable<Category> categories = new List<Category>();

            using (var client = new HttpClient())
            {
                using (var response = await client.GetAsync($"https://localhost:7147/api/Category"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    var responseObject = JsonConvert.DeserializeAnonymousType(apiResponse, new { data = Enumerable.Empty<Category>() });

                    categories = responseObject.data;
                }
            }

            var model = new TagIndexViewModel{ 
                PaginatedList = paginatedList,
                Categories = categories
            };

            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            var userRole = await GetUserRole();

            if (!userRole.Equals("Admin"))
            {
                return Redirect("https://localhost:7147/Identity/Account/Login?from=r");
            }

            try
            {
                var tag = new Tag();

                using (var client = new HttpClient())
                {
                    using (var response = await client.GetAsync($"https://localhost:7147/api/Tag/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            string result = await response.Content.ReadAsStringAsync();
                            tag = JsonConvert.DeserializeObject<Tag>(result);
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }

                IEnumerable<ShortRecipe> recipes = new List<ShortRecipe>();

                using (var client = new HttpClient())
                {
                    using (var response = await client.GetAsync($"https://localhost:7147/api/Recipe/tag/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            recipes = JsonConvert.DeserializeObject<List<ShortRecipe>>(apiResponse);
                        }
                    }
                }

                var model = new DetailTagViewModel
                {
                    Tag = tag,
                    Recipes = recipes
                };

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return RedirectToAction("Index");
            }
        }


        //GET
        public async Task<IActionResult> Create()
        {
            var userRole = await GetUserRole();

            if (!userRole.Equals("Admin"))
            {
                return Redirect("https://localhost:7147/Identity/Account/Login?from=r");
            }

            IEnumerable<Category> categories = new List<Category>();

            using (var client = new HttpClient())
            {
                using (var response = await client.GetAsync($"https://localhost:7147/api/Category"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    var responseObject = JsonConvert.DeserializeAnonymousType(apiResponse, new { data = Enumerable.Empty<Category>()});

                    categories = responseObject.data;
                }
            }

            var model = new CreateTagViewModel
            {
                Tag = new Tag(),
                Categories = categories
            };

            return View(model);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tag tag)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    var response = await client.PostAsync("https://localhost:7147/api/Tag",
                        new StringContent(JsonConvert.SerializeObject(tag), Encoding.UTF8, "application/json"));

                    return await HandleResponse(response, tag);
                }
            }
            catch (Exception ex)
            {
                // Log or handle unexpected exceptions
                ModelState.AddModelError(string.Empty, $"An error occurred: {ex.Message}");
                return View(tag);
            }
        }

        // GET
        public async Task<IActionResult> Edit(int? id)
        {
            var userRole = await GetUserRole();

            if (!userRole.Equals("Admin"))
            {
                return Redirect("https://localhost:7147/Identity/Account/Login?from=r");
            }

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var tag = new Tag();

            using (var client = new HttpClient())
            {
                using (var response = await client.GetAsync($"https://localhost:7147/api/Tag/{id}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        string result = await response.Content.ReadAsStringAsync();
                        tag = JsonConvert.DeserializeObject<Tag>(result);
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            var model = new CreateTagViewModel
            {
                Tag = tag,
                Categories = await GetCategories()
            };

            return View(model);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Tag tag)
        {
            try
            {
                var id = tag.Id;
                using (var client = new HttpClient())
                {
                    var response = await client.PutAsync($"https://localhost:7147/api/Tag/{id}",
                        new StringContent(JsonConvert.SerializeObject(tag), Encoding.UTF8, "application/json"));
                    _logger.LogInformation("Handling Response");
                    return await HandleResponse(response, tag);
                }
            }
            catch (Exception ex)
            {
                // Log or handle unexpected exceptions
                ModelState.AddModelError(string.Empty, $"An error occurred: {ex.Message}");
                return View(tag);
            }
        }

        private async Task<IActionResult> HandleResponse(HttpResponseMessage response, Tag tag)
        {
            _logger.LogInformation($"Response: {response.StatusCode}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            var result = await response.Content.ReadAsStringAsync();

            var model = new CreateTagViewModel
            {
                Tag = tag,
                Categories = await GetCategories()
            };

            if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                // Handle validation errors from the API

Flavorique MVC/Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Flavorique MVC/Views/Shared/_CKEditorScriptsPartial.cshtml
@{
    var tokenUrl = "https://localhost:7147/api/CKBox/token";
}

<script src="https://cdn.ckbox.io/ckbox/2.2.0/ckbox.js"></script>
<script src="~/assets/vendor/build/ckeditor.js"></script>
<script>
    let bodyData = document.querySelector("#bodyData").children[1].value
    bodyData = bodyData.replace("image widget", "");
    bodyData = bodyData.replace(". Press Enter to type after or press Shift + Enter to type before the widget", "");

    let editor;

    ClassicEditor
        .create(document.querySelector('#editor'), {
            ckbox: {
                tokenUrl: '@tokenUrl',
                theme: 'lark'
            },
            removePlugins: ['FormatPainter', 'Table'],
        })
        .then(newEditor => {
            newEditor.setData(bodyData);
            editor = newEditor;
        })
        .catch(error => {
            console.log(error);
        });

    function setValues() {
        let ckContent = document.querySelector(".ck-content");
        let body = ckContent.innerHTML;
        body.replace("image widget. Press Enter to type after or press Shift + Enter to type before the widget", "");

        let bodyInput = document.querySelector(".body-input");
        bodyInput.value = body;
    }
</script>

Flavorique MVC/Views/Shared/_Layout.cshtml
@functions {
    private bool IsCurrentPage(string page)
    {
        var currentUrl = Context.Request.Path;
        return currentUrl.Equals(page, StringComparison.OrdinalIgnoreCase);
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flavorique</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><img height="35px" src="https://localhost:7147/logo" /> Flavorique</a>
                <button class="navbar-toggler text-light" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-light"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-flex justify-content-end">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="d-flex flex-column flex-shrink-0 text-white bg-dark position-absolute overflow-hidden sidebar z-3" style="width: 280px; height: calc(100% - 61px); padding: 1rem; transition: 0.2s all ease-in;">
        <div class="d-flex">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-4">Navigate</span>
        </a>
            <button onClick="closeSidebar()" class="btn btn-danger p-0" style="width: 25px; height: 25px; align-self: flex-start;"><i class="bi bi-x"></i></button>

        </div>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/") ? "bg-primary" : "")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/Account") ? "bg-primary" : "")" asp-area="" asp-controller="Account" asp-action="Index">Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/Category") ? "bg-primary" : "")" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/Tag") ? "bg-primary" : "")" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/Recipe") ? "bg-primary" : "")" asp-area="" asp-controller="Recipe" asp-action="Index">Recipes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light @(IsCurrentPage("/Comment") ? "bg-primary" : "")" asp-area="" asp-controller="Comment" asp-action="Index">Comments</a>
            </li>
        </ul>
    </div>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Flavorique - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>

        function closeSidebar() { 
            let sidebar = document.querySelector(".sidebar");
            sidebar.style.width = "0px";
            sidebar.style.padding = "0px";
        }

        document.addEventListener('mousemove', function (event) {
            var mouseX = event.clientX;
            if (mouseX <= 20) {
                let sidebar = document.querySelector(".sidebar");
                sidebar.style.width = "280px";
                sidebar.style.padding = "1rem";
            } 
        });
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Flavorique MVC/Views/Shared/_TagInputScriptsPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script>
    function createTagSpan(value, text) {
        const tagSpan = document.createElement('span');
        tagSpan.classList.add('btn', 'btn-primary', 'me-2');
        tagSpan.textContent = text; 
        tagSpan.setAttribute('data-value', value);
        tagSpan.addEventListener('click', () => removeTag(tagSpan));

        return tagSpan;
    }

    function initializeSpans() {
        const selectedTagsDiv = document.getElementById('selectedTags');
        const selectedTagsInput = document.getElementById('selectedTagsInput');

        const inputValues = selectedTagsInput.value.trim();

        if (inputValues !== '') {
            const valuesArray = inputValues.split(',').map(value => value.trim());

            valuesArray.forEach(value => {

                const option = Array.from(tagSelect.options).find(option => option.value === value);
                const tagSpan = createTagSpan(value, option.text);
                selectedTagsDiv.appendChild(tagSpan);
            });
        }
    }

    function addTag() {
        const tagSelect = document.getElementById('tagSelect');
        const selectedTagsDiv = document.getElementById('selectedTags');

        Array.from(tagSelect.selectedOptions).forEach(option => {
            if (!tagExists(selectedTagsDiv, option.value)) {
                const tagSpan = createTagSpan(option.value, option.text);
                selectedTagsDiv.appendChild(tagSpan);
            }
        });

        tagSelect.selectedIndex = 0;
        updateSelectedTagsInput();
    }

    function tagExists(selectedTagsDiv, value) {
        return Array.from(selectedTagsDiv.children).some(span => span.getAttribute('data-value') === value);
    }

    function removeTag(tagSpan) {
        const selectedTagsDiv = document.getElementById('selectedTags');
        selectedTagsDiv.removeChild(tagSpan);
        updateSelectedTagsInput();
    }

    function updateSelectedTagsInput() {
        const selectedTagsDiv = document.getElementById('selectedTags');
        const selectedTagsInput = document.getElementById('selectedTagsInput');

        const valuesArray = Array.from(selectedTagsDiv.children).map(span => span.getAttribute('data-value'));
        selectedTagsInput.value = valuesArray.join(', ');
    }

    initializeSpans();
</script>